#!/bin/sh
walldir=/home/joel/.config/awesome/themes/purple/wall.png
basedir=/home/joel/Pictures/wallpapers
curdir="$PWD"
arg="$1"
wall=$(/bin/ls $basedir|sed s/@$//g|shuf|head -n 1)


[ -z  "$arg" ] && feh --bg-fill "$basedir/$wall" && cp "$basedir/$wall" "$walldir" && flag=1 

[ "$arg" = "--choose" ] &&  sxiv -t  $(realpath $basedir/*|shuf) > /dev/null 2>&1 && feh --bg-fill "$(xclip -o)" > /dev/null 2>&1 && cp "$(xclip -o)" "$walldir"  && flag=1 || [ ! -z "$arg" ] && feh --bg-fill "$curdir/$arg" > /dev/null 2>&1 && cp "$curdir/$arg" "$walldir" && flag=1

[ ! -z "$flag" ] && notify-send "Wallpaper Changed🌆"

