#!/usr/bin/env bash
[ -e ~/phone ] && rm -rf ~/phone 
mkdir -p ~/phone 

opt=$(simple-mtpfs -l |dmenu -fn "manrope-10" -nb black -sb "#260A35" -i -p "which device do you want to mount?"|cut -c 1)
simple-mtpfs --device "$opt" ~/phone && notify-send "📱mounted Sucessfully!"
