#!/bin/bash
shopt -s expand_aliases

CACHE="$HOME/.cache/pdfcache"
[ ! -f "$CACHE" ] && touch "$CACHE"

if [ -f "$1" ]; then
    pageline="$(realpath "$1")"
    fored="$(printf "%b" "$pageline" | sed 's,/,\\/,g')"
    if grep -q -F "$pageline" "$CACHE"; then
	
	printf "%b\n" "/$fored/d\nw" | ed -s "$CACHE" 
    else 
	page=1
    fi
    zathura "$1" 
	printf "%b\n" "0a\n$pageline\n.\nw" | ed -s "$CACHE"
else
    exit 1
fi



