#!/bin/sh

first=~/Music/
song="$(realpath ~/Music/* ~/Music/*/* ~/Music/*/*/* ~/Music/*/*/*/*|grep .[mw][eokp4][abv43]|sed s/"\/home\/joel\/Music\/"//g|shuf|rofi -dmenu -i -p "music 🎶")" && /usr/bin/clementine --play "$first$song" > /dev/null 2>&1 & disown
##addded shuffling of list 
