#!/bin/bash
#Minimal script to download a youtube video/audio using youtube-dl and rename the file to preferred file name
     link=$1
     query="_-$(echo $link|cut -c 33-)" 
     read -p "Enter Title of the video📺:" title
     youtube-dl "$link" && rename s/"$query"/"$title"/g *
 

