#!/bin/sh
walldir=/home/joel/.config/awesome/themes/purple/wall.png
dir=/home/joel/Pictures/wallpapers
curdir=$PWD
arg=$1
wall=$(/bin/ls $dir|sed s/@$//g|shuf|head -n 1)


[ -z  "$arg" ] && feh --bg-fill "$dir/$wall" && cp "$dir/$wall" "$walldir" && flag=1 


[ "$arg" = "--choose" ] && sxiv -t  $(realpath $dir/*|shuf) > /dev/null 2>&1 && feh --bg-fill "$(xclip -o)" > /dev/null 2>&1 && cp "$(xclip -o)" "$walldir"  && flag=1 || [ ! -z "$arg" ] && feh --bg-fill "$curdir/$arg" > /dev/null 2>&1 && cp "$curdir/$arg" "$walldir" && flag=1

[ ! -z $flag ] && notify-send "Wallpaper Changed🌆"

