#!/bin/bash

query=$(echo|dmenu -fn "iosevka-11" -nb black -sb "#260A35" -p "Search 😃:") && choice=$(printf "Duckduckgo\nGoogle\nGithub\nArch Wiki"|dmenu -fn "iosevka-11" -nb black -sb "#260A35" -p "Search with ?") 

googles(){
    chromium "https://www.google.com/search?q=$query"
}

duckduckgo(){
    chromium "https://www.duckduckgo.com/?q=$query"
}
github(){
    chromium "https://github.com/search?q=$query"
}
archwiki(){
    chromium "https://wiki.archlinux.org/index.php?search=$query"
}


if [ $choice == 'Duckduckgo' ]; then
    duckduckgo
elif [ "$choice" == "Google" ]; then
    googles
elif [ "$choice" == "Github" ]; then
    github
elif [ "$choice" == "Arch Wiki" ]; then
    archwiki
else
    echo > /dev/null
fi


