#!/bin/bash
HISTFILE=~/.bash_history
set -o history
history > "/home/joel/scripts/history";sed  -i s/"[0-9]\+ "//g "/home/joel/scripts/history" 
$(tac  /home/joel/scripts/history|dmenu -nb black -sb "#260A35"' )
