#!/usr/bin/env bash
[ -f ~/phone ] && rm ~/phone 
mkdir -p ~/phone 

simple-mtpfs -l >~/anddev
opt=$(cat ~/anddev|dmenu -fn "manrope-10" -nb black -sb "#260A35" -i -p "which device do you want to mount?"|cut -c 1)
simple-mtpfs --device "$opt" ~/phone && notify-send "📱mounted Sucessfully!"
