#!/bin/bash
shopt -s expand_aliases
alias dmenu='dmenu -fn "manrope-10" -nb black -sb "#260A35"'


# mupdf() { command mupdf -I -r 100 "$@" > /dev/null 2>&1 & disown ;}
CACHE="$HOME/.cache/pdfcache"
[ ! -f "$CACHE" ] && touch "$CACHE"

if [ -f "$1" ]; then
    pageline="$(realpath "$1")"
    fored="$(printf "%b" "$pageline" | sed 's,/,\\/,g')"
    if grep -q -F "$pageline" "$CACHE"; then
	page=$(grep "$pageline" "$CACHE" | cut -f 2)
	printf "%b\n" "/$fored/d\nw" | ed -s "$CACHE" 
    else 
	page=1
    fi
    mupdf -I -r 150 "$1" $page &
    wait
    input=$(echo "$page"|dmenu -l 0 -p "$(basename -s .pdf "$1")" 2>/dev/null)
    
    case $input in
	''|*[!0-9]*) page=$page;;
	*) page=$input;;
    esac
	printf "%b\n" "0a\n$pageline\t$page\n.\nw" | ed -s "$CACHE"
else
    exit 1
fi


epubs(){
pdf $(ls *.epub|dmenu -nb black -l 30)
}

