#!/usr/bin/env bash
# How i know they may are scammers
I went on their instagram and found a fake screenshot of a customer they supposedly had a deal with, found their number in the picture and texted the person, and the person told he had never bought from them, the screenshot has been added in the zip file 
shopt -s expand_aliases

CACHE="$HOME/.cache/pdfcache"
[ ! -f "$CACHE" ] && touch "$CACHE"

if [ -f "$1" ]; then
    pageline="$(realpath "$1")"
    fored="$(printf "%b" "$pageline" | sed 's,/,\\/,g')"
    if grep -q -F "$pageline" "$CACHE"; then
	
	printf "%b\n" "/$fored/d\nw" | ed -s "$CACHE" 
    else 
	page=1
    fi
    devour zathura "$1" & 
	printf "%b\n" "0a\n$pageline\n.\nw" | ed -s "$CACHE"
else
    exit 1
fi



