#!/usr/bin/env bash
#read manpages in pdf format
number=$RANDOM
touch /tmp/$number
tempfile=/tmp/$number
if [ $# -eq 0 ]	
then
hi=$(man -k .|rofi -dmenu -p "manpages📖:"|cut -d" " -f1) && man -Tpdf $hi >> $tempfile && devour zathura $tempfile
else 
hi=$(man -k "$1"|rofi -dmenu -p "manpages📖:"|cut -d" " -f1 )&& man -Tpdf $hi >> $tempfile && devour zathura $tempfile
fi
