#!/bin/bash

query=$(echo|dmenu -fn "manrope-10" -nb black -sb "#260A35" -p "Search 😃:") && choice=$(printf "Duckduckgo\nGoogle\nYoutube\nLibrary\nReddit\nGithub\nArch Wiki"|dmenu -fn "manrope-10" -nb black -sb "#260A35" -p "Search with ?") 



google(){
    firefox-esr "https://www.google.com/search?q=$query"
}
youtube(){
    firefox-esr "https://www.youtube.com/results?search_query=$query"
}
duckduckgo(){
    firefox-esr "https://www.duckduckgo.com/?q=$query"
}
github(){
    firefox-esr "https://github.com/search?q=$query"
}
archwiki(){
    firefox-esr "https://wiki.archlinux.org/index.php?search=$query"
}
reddit(){
    firefox-esr "https://www.reddit.com/search/?q=$query"
}
lib(){
    firefox-esr "http://gen.lib.rus.ec/search.php?req=$query"
}

#https://www.techopedia.com/search?q=

if [ $choice == 'Duckduckgo' ]; then
    duckduckgo
elif [ "$choice" == "Google" ]; then
    google
elif [ "$choice" == "Github" ]; then
    github
elif [ "$choice" == "Arch Wiki" ]; then
    archwiki
elif [ "$choice" == "Youtube" ]; then
    youtube
elif [ "$choice" == "Reddit" ]; then
    reddit
elif [ "$choice" == "Library" ]; then
    lib
else
    echo > /dev/null
fi


