#!/bin/bash
shopt -s expand_aliases
alias dmenu='dmenu -l 30 -nb black -sb "#260A35"'
declare -A booklist; declare -a index
while read i; do
    location="$i"
    title="${i##*/}"
    booklist[$title]="$location"; index+=( "$title" )
done < <(cat "$HOME/.cache/pdfcache" | cut -f 1)
select="$(printf '%s\n' "${index[@]}" | dmenu -p pdf)"
[ -z "$select" ] && exit 1
exec ~/scripts/pdf "${booklist[$select]}" &
exit 0
