#!/bin/bash

#insert into patient(cname,coursereg,courseyear,coursedesc) values ("Joel","Amoako","Kwabenya","0541053593")
i=1;
while [ $i -lt 20 ]; do
_cname=$(awk  '{print $1}' /home/joel/randomdata/Course|sed $i!d)
_coursereg=$(awk  '{print $2}' /home/joel/randomdata/Course|sed $i!d)
_courseyear=$(awk  '{print $3}' /home/joel/randomdata/Course|sed $i!d)
_coursedesc=$(awk  '{print $4}' /home/joel/randomdata/Course|sed $i!d)
#_blockfloor=$(awk  '{print $3}' /home/joel/randomdata/Course|sed $i!d)
    ((i++))
mysql schooldb << end
INSERT INTO  Course(cname,coursereg,courseyear,coursedesc) VALUES ('$_cname', $_coursereg, $_courseyear,$_coursedesc);
end
done
