#!/bin/bash

#insert into patient(cname,coursereg,courseyear,coursedesc) values ("Joel","Amoako","Kwabenya","0541053593")
i=1;
while [ $i -lt 8 ]; do
name=$(awk  '{print $4 " " $5}' /home/joel/data|sed $i!d)
ssn=$(awk  '{print $6}' /home/joel/data|sed $i!d)
address=$(awk  '{print $7}' /home/joel/data|sed $i!d)
officephone=$(awk  '{print $8}' /home/joel/data|sed $i!d)
age=$(awk  '{print $9}' /home/joel/data|sed $i!d)
gpa=$(awk  '{print $10}' /home/joel/data|sed $i!d)
major=$(awk  '{print $11}' /home/joel/data|sed $i!d)
    ((i++))
mysql schooldb << EOF
INSERT INTO  Student(name,ssn,address,officephone,age,gpa,major) VALUES ("$name","$ssn","$address","$officephone","$age","$gpa","$major") 

EOF
done
