#!/usr/bin/env bash
#Minimal script to download a youtube video/audio using youtube-dl and rename the file to preferred file name
  #     link=$1
   #    query="_-$(echo $link|cut -c 33-)" 
  #     read -p "Enter Title of the video📺:" title
   #    youtube-dl "$link" && rename s/"$query"/"$title"/g *
 
link=$2
     query="-$(echo $link|cut -c 33-)" 
     vid(){  youtube-dl -f best  "$link" && rename s/"$query"//g *
     }
 audio(){
 youtube-dl -f bestaudio "$link" && rename s/"$query"//g *

 }

if [ "$1" = "audio" ]; then
    audio
elif [ "$1" = "video" ]; then 
vid
else 
    vid 
    fi
